route:
  receiver: email-notifications

receivers:
- name: email-notifications
  email_configs:
  - to: your-email@gmail.com
    from: your-email@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "your-email@gmail.com"
    auth_password: "your-app-password"
    require_tls: true